# Generated by Django 4.1 on 2022-09-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ego',
            old_name='ego_cog_apt',
            new_name='cog',
        ),
        migrations.RenameField(
            model_name='ego',
            old_name='ego_int_apt',
            new_name='inte',
        ),
        migrations.RenameField(
            model_name='ego',
            old_name='ego_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ego',
            old_name='ego_ref_apt',
            new_name='ref',
        ),
        migrations.RenameField(
            model_name='ego',
            old_name='ego_sav_apt',
            new_name='sav',
        ),
        migrations.RenameField(
            model_name='ego',
            old_name='ego_som_apt',
            new_name='som',
        ),
        migrations.RenameField(
            model_name='ego',
            old_name='ego_wil_apt',
            new_name='wil',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_complexity_gp',
            new_name='complexity_gp',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='morph',
            old_name='morph_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='morph',
            old_name='morph_name',
            new_name='mtype',
        ),
        migrations.RenameField(
            model_name='morph',
            old_name='morph_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='ego_a_rep',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='ego_c_rep',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='ego_f_rep',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='ego_flex',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='ego_g_rep',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='ego_i_rep',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='ego_r_rep',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='ego_x_rep',
        ),
        migrations.RemoveField(
            model_name='item',
            name='egos',
        ),
        migrations.RemoveField(
            model_name='morph',
            name='egos',
        ),
        migrations.AddField(
            model_name='ego',
            name='items',
            field=models.ManyToManyField(to='character_generator.item'),
        ),
        migrations.AddField(
            model_name='ego',
            name='morph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character_generator.morph'),
        ),
        migrations.DeleteModel(
            name='Character_Sheet',
        ),
    ]
