# Generated by Django 4.1 on 2022-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "character_generator",
            "0004_morph_avail_morph_desc_morph_dr_morph_dur_morph_flex_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("base", models.IntegerField(default=0)),
                ("full", models.IntegerField(default=0)),
            ],
        ),
    ]
